# Generated by Django 6.1 on 2026-09-02 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('jam_operasional', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Kontak',
                'verbose_name_plural': 'Kontak',
            },
        ),
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('singkatan', models.CharField(help_text='Contoh: HKP, KPPHI, PPHI, BMHI', max_length=30)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil di bagan struktur beranda')),
                ('deskripsi_beranda', models.TextField(blank=True, help_text='Ringkasan yang tampil di tab Beranda unit ini')),
                ('tusi', models.TextField(blank=True, verbose_name='Tugas dan Fungsi')),
                ('struktur_organisasi_gambar', models.ImageField(blank=True, null=True, upload_to='struktur_organisasi/')),
                ('struktur_organisasi_keterangan', models.TextField(blank=True, help_text='Teks pelengkap/daftar jabatan (opsional)')),
            ],
            options={
                'verbose_name': 'Unit Kerja',
                'verbose_name_plural': 'Unit Kerja',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='UnitAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_profile', to=settings.AUTH_USER_MODEL)),
                ('unit_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profiles', to='konten.unitkerja')),
            ],
            options={
                'verbose_name': 'Profil Admin Unit',
                'verbose_name_plural': 'Profil Admin Unit',
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Terbit')], default='draft', max_length=10)),
                ('tanggal_publish', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berita_list', to='konten.unitkerja')),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
                'ordering': ['-tanggal_publish'],
            },
        ),
    ]
