# Generated by Django 6.1 on 2026-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilDitjen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dirjen', models.CharField(blank=True, help_text='Nama pejabat Direktur Jenderal (tampil di puncak bagan)', max_length=150)),
                ('paragraf_1', models.TextField(blank=True, help_text='Paragraf definisi Ditjen (kalimat pertama panel beranda)')),
                ('paragraf_2', models.TextField(blank=True, help_text='Paragraf kedua (tentang kepemimpinan Ditjen)')),
                ('tupoksi', models.TextField(blank=True, help_text='Daftar tugas dan fungsi (a, b, c, ...) — tulis lengkap dengan huruf, satu poin per baris')),
            ],
            options={
                'verbose_name': 'Profil Ditjen',
                'verbose_name_plural': 'Profil Ditjen',
            },
        ),
        migrations.AddField(
            model_name='unitkerja',
            name='jabatan',
            field=models.CharField(blank=True, help_text='Contoh: Sekretaris Ditjen PHI-JSK, Direktur Bina Mediator...', max_length=100),
        ),
        migrations.AddField(
            model_name='unitkerja',
            name='nama_pejabat',
            field=models.CharField(blank=True, help_text='Nama pejabat yang menjabat (tampil di bagan struktur beranda)', max_length=150),
        ),
    ]
