# Generated by Django 6.1 on 2026-09-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0002_profilditjen_unitkerja_jabatan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilditjen',
            name='tupoksi',
        ),
        migrations.AddField(
            model_name='profilditjen',
            name='tupoksi_a',
            field=models.TextField(blank=True, verbose_name='Tupoksi — poin a'),
        ),
        migrations.AddField(
            model_name='profilditjen',
            name='tupoksi_b',
            field=models.TextField(blank=True, verbose_name='Tupoksi — poin b'),
        ),
        migrations.AddField(
            model_name='profilditjen',
            name='tupoksi_c',
            field=models.TextField(blank=True, verbose_name='Tupoksi — poin c'),
        ),
        migrations.AddField(
            model_name='profilditjen',
            name='tupoksi_d',
            field=models.TextField(blank=True, verbose_name='Tupoksi — poin d'),
        ),
        migrations.AddField(
            model_name='profilditjen',
            name='tupoksi_e',
            field=models.TextField(blank=True, verbose_name='Tupoksi — poin e'),
        ),
        migrations.AddField(
            model_name='profilditjen',
            name='tupoksi_f',
            field=models.TextField(blank=True, verbose_name='Tupoksi — poin f'),
        ),
        migrations.AddField(
            model_name='profilditjen',
            name='tupoksi_g',
            field=models.TextField(blank=True, verbose_name='Tupoksi — poin g'),
        ),
        migrations.AddField(
            model_name='profilditjen',
            name='tupoksi_pembuka',
            field=models.CharField(blank=True, help_text="Kalimat pembuka sebelum daftar poin, contoh: '...menyelenggarakan fungsi:'", max_length=300),
        ),
    ]
