# Generated by Django 6.1 on 2026-09-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0003_remove_profilditjen_tupoksi_profilditjen_tupoksi_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Contoh: 'Ketua Tim Kerja pembinaan hubungan kerja' atau 'wakil ketua Tim Kerja bidang ...'", max_length=255)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('induk', models.ForeignKey(blank=True, help_text='Kosongkan untuk Ketua Tim Kerja. Isi (pilih Ketua Tim Kerja yang sesuai) untuk Wakil Ketua.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='konten.timkerja')),
                ('unit_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tim_kerja_list', to='konten.unitkerja')),
            ],
            options={
                'verbose_name': 'Tim Kerja',
                'verbose_name_plural': 'Tim Kerja',
                'ordering': ['urutan', 'id'],
            },
        ),
    ]
