# Generated by Django 6.1 on 2026-09-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0004_timkerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontak',
            name='facebook',
            field=models.URLField(blank=True, help_text='Link lengkap, contoh: https://facebook.com/kemnaker'),
        ),
        migrations.AddField(
            model_name='kontak',
            name='instagram',
            field=models.URLField(blank=True, help_text='Link lengkap, contoh: https://instagram.com/kemnaker'),
        ),
        migrations.AddField(
            model_name='kontak',
            name='tiktok',
            field=models.URLField(blank=True, help_text='Link lengkap, contoh: https://tiktok.com/@kemnaker'),
        ),
        migrations.AddField(
            model_name='kontak',
            name='twitter_x',
            field=models.URLField(blank=True, help_text='Link lengkap, contoh: https://x.com/kemnaker', verbose_name='X (Twitter)'),
        ),
        migrations.AddField(
            model_name='kontak',
            name='youtube',
            field=models.URLField(blank=True, help_text='Link lengkap, contoh: https://youtube.com/@kemnaker'),
        ),
    ]
