# Generated by Django 6.1 on 2026-09-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0005_kontak_facebook_kontak_instagram_kontak_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontak',
            name='whatsapp_group',
            field=models.URLField(blank=True, help_text='Link undangan grup, contoh: https://chat.whatsapp.com/xxxxxxxxxxxxx', verbose_name='Grup WhatsApp'),
        ),
    ]
