# Generated by Django 6.1 on 2026-09-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0006_kontak_whatsapp_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontak',
            name='whatsapp_group',
            field=models.URLField(blank=True, help_text='Link undangan channel, contoh: https://whatsapp.com/channel/xxxxxxxxxxxxx', verbose_name='Channel WhatsApp'),
        ),
    ]
