# Generated by Django 6.1 on 2026-09-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konten", "0007_alter_kontak_whatsapp_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="berita",
            options={
                "ordering": ["-tanggal_publish"],
                "verbose_name": "Informasi",
                "verbose_name_plural": "Informasi",
            },
        ),
        migrations.CreateModel(
            name="Komentar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100, verbose_name="Nama")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Opsional, tidak ditampilkan publik",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                ("isi", models.TextField(verbose_name="Komentar")),
                (
                    "disetujui",
                    models.BooleanField(default=False, verbose_name="Disetujui"),
                ),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                (
                    "berita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="komentar_list",
                        to="konten.berita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komentar",
                "verbose_name_plural": "Komentar",
                "ordering": ["-dibuat_pada"],
            },
        ),
    ]
