# Generated by Django 6.1 on 2026-09-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konten", "0008_alter_berita_options_komentar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="komentar",
            options={
                "ordering": ["dibuat_pada"],
                "verbose_name": "Komentar",
                "verbose_name_plural": "Komentar",
            },
        ),
        migrations.RemoveField(
            model_name="komentar",
            name="disetujui",
        ),
        migrations.AddField(
            model_name="komentar",
            name="is_admin_reply",
            field=models.BooleanField(default=False, verbose_name="Balasan admin"),
        ),
        migrations.AddField(
            model_name="komentar",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balasan",
                to="konten.komentar",
                verbose_name="Membalas komentar",
            ),
        ),
    ]
